spring.application.name=Task-Management-System
spring.datasource.url=mysql://root:RYfzahDjsYaOOvfjlxIrfihxaeeQASjs@mysql.railway.internal:3306/railway
spring.datasource.username=root

# change user name and password as your system has your own

spring.datasource.password=RYfzahDjsYaOOvfjlxIrfihxaeeQASjs

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=8080
